/**
 * @file version.h
 *
 * @brief Version and metadata definitions for the Laser VST Plugin.
 *
 * This file defines the version information and metadata for the Laser VST
 * Plugin. It specifies details such as file descriptions, company information,
 * and legal copyright and trademark statements.
 *
 * @details
 * The version information defined here is used by the VST plugin to provide
 * metadata to the host environment. It supports platform-specific details
 * (e.g., 64-bit or 32-bit) and includes licensing information required for
 * distribution.
 *
 * Features:
 * - Defines file descriptions and versioning metadata.
 * - Platform-specific descriptions for 32-bit and 64-bit builds.
 * - Legal copyright and trademark notices.
 *
 * Dependencies:
 * - Steinberg VST3 SDK
 * - Platform macros provided by pluginterfaces/base/fplatform.h
 *
 * @copyright Radar2000
 * This work is licensed under Creative Commons
 * Attribution-NonCommercial-ShareAlike 4.0 International License.
 *
 * @author Radar2000
 */

#pragma once

#include "pluginterfaces/base/fplatform.h"  ///< Platform-specific definitions

// Plain project version file generated by CMake
#include "projectversion.h"  ///< Auto-generated version information

/**
 * @brief Defines the original file name for the plugin binary.
 */
#define stringOriginalFilename "Laser.vst3"

/**
 * @brief Provides a platform-specific file description for the plugin.
 */
#if SMTG_PLATFORM_64
#define stringFileDescription \
  "Laser VST3 (64Bit)"  ///< 64-bit build description
#else
#define stringFileDescription "Laser VST3"  ///< 32-bit build description
#endif

/**
 * @brief Defines the company name for metadata purposes.
 */
#define stringCompanyName "Radar\0"

/**
 * @brief Defines the legal copyright statement.
 */
#define stringLegalCopyright "Copyright(cc) Radar."

/**
 * @brief Defines legal trademark information.
 */
#define stringLegalTrademarks \
  "VST is a trademark of Steinberg Media Technologies GmbH"
